# Generated by Django 4.0.4 on 2022-04-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('N', 'Nature'), ('V', 'Visit'), ('T', 'Tour')], default='N', max_length=1)),
            ],
        ),
    ]
