# Generated by Django 4.0.4 on 2022-04-26 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='thing',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='main_app.thing'),
            preserve_default=False,
        ),
    ]
