# Generated by Django 4.0.4 on 2022-04-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_events_thing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='thing',
            name='programs',
            field=models.ManyToManyField(to='main_app.program'),
        ),
    ]
