# Generated by Django 4.0.4 on 2022-04-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_program_thing_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='kind',
            field=models.CharField(max_length=100),
        ),
    ]
